# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-14 17:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0002_article_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='date',
            field=models.DateField(default='2017.01.01'),
        ),
    ]
