# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-14 17:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0005_article_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='present_page_text',
            field=models.CharField(default = '', max_length=200),
        ),
    ]
