# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-24 15:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact_us', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contacts',
            name='name',
            field=models.CharField(default='', max_length=60),
        ),
    ]
